"use client";
import { useState } from "react";
import { CartesianGrid, Line, LineChart, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { DailyReportMetrics } from "@/types/report";
type Metric = "operatingResult" | "grossIncome" | "expenses";
const options: Array<{ key: Metric; label: string; aria: string }> = [{ key: "operatingResult", label: "Resultado", aria: "resultado" }, { key: "grossIncome", label: "Ingresos", aria: "ingresos" }, { key: "expenses", label: "Gastos", aria: "gastos" }];
const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
export function ReportTrendChart({ selectedMonth, previousMonth, daily }: { selectedMonth: string; previousMonth: string; daily: Array<{ day: number; selected: DailyReportMetrics; previous: DailyReportMetrics | null }> }) { const [metric, setMetric] = useState<Metric>("operatingResult"); const option = options.find((o) => o.key === metric)!; const data = daily.map((d) => ({ day: d.day, selected: d.selected[metric], previous: d.previous?.[metric] ?? null })); const total = data.reduce((sum, d) => sum + d.selected, 0); const ariaMetric = metric === "operatingResult" ? "del resultado" : `de ${option.aria}`; return <Card className="bg-white"><CardHeader className="flex-row flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">Evolución diaria</CardTitle><div className="flex rounded-xl bg-muted p-1">{options.map((o) => <Button key={o.key} size="sm" variant={metric === o.key ? "default" : "ghost"} onClick={() => setMetric(o.key)}>{o.label}</Button>)}</div></CardHeader><CardContent><div className="overflow-x-auto"><div role="img" aria-label={`Evolución diaria ${ariaMetric}: ${selectedMonth} comparado con ${previousMonth}`} className="min-w-[680px]"><LineChart responsive accessibilityLayer data={data} style={{ width: "100%", height: 320 }}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis tickFormatter={(value) => `$${Math.round(Number(value) / 1000)}k`} /><Tooltip formatter={(value) => money.format(Number(value))} /><Line type="monotone" dataKey="selected" name={selectedMonth} stroke="#55745b" strokeWidth={3} dot={false} isAnimationActive={false} /><Line type="monotone" dataKey="previous" name={previousMonth} stroke="#a6a6a1" strokeDasharray="5 5" dot={false} isAnimationActive={false} /></LineChart></div></div><p className="mt-3 text-sm text-muted-foreground">{selectedMonth} acumula {money.format(total)} en {option.label.toLowerCase()}.</p></CardContent></Card>; }
