"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { expenseCategoryClient as defaultClient, type ExpenseCategoryClient } from "@/lib/expenses/client";
import { createExpenseCategorySchema } from "@/lib/expenses/schemas";
import type { ExpenseCategory, ExpenseCategoryType } from "@/types/expense";
const labels = { fixed: "Fijo", variable: "Variable", supplies: "Insumos" };
export const ExpenseCategoriesDialog = ({ categories, onChange, onClose, client = defaultClient }: { categories: ExpenseCategory[]; onChange(value: ExpenseCategory[]): void; onClose(): void; client?: ExpenseCategoryClient }) => {
  const [name, setName] = useState(""); const [type, setType] = useState<ExpenseCategoryType>("variable"); const [editing, setEditing] = useState<string | null>(null); const [confirmation, setConfirmation] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const run = async (action: () => Promise<void>, message: string) => { setPending(true); setError(null); try { await action(); toast.success(message); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo actualizar la categoría."); } finally { setPending(false); } };
  const save = () => run(async () => { const parsed = createExpenseCategorySchema.parse({ name, type }); if (editing) { const updated = await client.update(editing, parsed); onChange(categories.map((item) => item.id === editing ? updated : item)); } else { onChange([...categories, await client.create(parsed)]); } setName(""); setEditing(null); }, editing ? "Categoría actualizada." : "Categoría creada.");
  const control = "h-10 rounded-xl border border-input bg-white px-3 text-sm";
  return <Dialog open onOpenChange={(open) => !open && !pending && onClose()}><DialogContent className="max-h-[90svh] overflow-y-auto rounded-[1.6rem] p-5 sm:max-w-2xl"><DialogHeader><DialogTitle>Administrar categorías</DialogTitle><DialogDescription>Organizá los gastos por naturaleza. Las categorías usadas deben desactivarse en lugar de eliminarse.</DialogDescription></DialogHeader><div className="grid gap-2 sm:grid-cols-[1fr_150px_auto]"><Input aria-label="Nombre de categoría" placeholder="Nueva categoría" value={name} onChange={(e) => setName(e.target.value)} /><select aria-label="Tipo de categoría" className={control} value={type} onChange={(e) => setType(e.target.value as ExpenseCategoryType)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button type="button" disabled={pending} onClick={save}>{editing ? "Guardar" : "Crear"}</Button></div>{error && <p role="alert" className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error} Si tiene gastos asociados, desactivala para conservar el historial.</p>}<div className="space-y-2">{categories.map((category) => <article key={category.id} className="rounded-2xl border bg-white p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{category.name}</p><p className="text-xs text-muted-foreground">{labels[category.type]} · {category.isActive ? "Activa" : "Inactiva"}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => { setEditing(category.id); setName(category.name); setType(category.type); }}>Editar</Button><Button size="sm" variant="outline" onClick={() => run(async () => { const updated = await client.update(category.id, { isActive: !category.isActive }); onChange(categories.map((item) => item.id === category.id ? updated : item)); }, category.isActive ? "Categoría desactivada." : "Categoría reactivada.")}>{category.isActive ? "Desactivar" : "Reactivar"}</Button></div></div><div className="mt-3 flex gap-2"><Input aria-label={`Confirmar eliminación de ${category.name}`} placeholder={`Escribí ${category.name}`} value={confirmation[category.id] ?? ""} onChange={(e) => setConfirmation((value) => ({ ...value, [category.id]: e.target.value }))} /><Button variant="destructive" size="sm" disabled={pending || confirmation[category.id] !== category.name} onClick={() => run(async () => { await client.remove(category.id); onChange(categories.filter((item) => item.id !== category.id)); }, "Categoría eliminada.")}>Eliminar</Button></div></article>)}</div></DialogContent></Dialog>;
};
