"use client";
import { Plus, ReceiptText, Settings2, WalletCards } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { ExpenseCategoriesDialog } from "@/components/expenses/expense-categories-dialog";
import { ExpenseDetailSheet } from "@/components/expenses/expense-detail-sheet";
import { ExpenseEditorDialog } from "@/components/expenses/expense-editor-dialog";
import { ExpenseVoidDialog } from "@/components/expenses/expense-void-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { expenseClient as defaultClient, type ExpenseCategoryClient, type ExpenseClient } from "@/lib/expenses/client";
import { getMonthBounds } from "@/lib/expenses/date";
import type { Expense, ExpenseCategory, ExpenseCategoryType, ExpenseDetail, ExpenseListQuery, ExpenseMonthSummary, PaginatedExpenses } from "@/types/expense";
import type { PaymentMethod } from "@/types/payment-method";
const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
const typeLabels = { fixed: "Fijos", variable: "Variables", supplies: "Insumos" };
type Filters = { categoryId: string; type: string; dateFrom: string; dateTo: string; text: string; status: string; paymentMethodId: string };
const emptyFilters: Filters = { categoryId: "", type: "", dateFrom: "", dateTo: "", text: "", status: "active", paymentMethodId: "" };
export const ExpensesWorkspace = ({ initialData, initialSummary, initialCategories, paymentMethods, initialMonth, today, client = defaultClient, categoryClient }: { initialData: PaginatedExpenses; initialSummary: ExpenseMonthSummary; initialCategories: ExpenseCategory[]; paymentMethods: PaymentMethod[]; initialMonth: string; today: string; client?: ExpenseClient; categoryClient?: ExpenseCategoryClient }) => {
  const [month, setMonth] = useState(initialMonth); const [summary, setSummary] = useState(initialSummary); const [result, setResult] = useState(initialData); const [categories, setCategories] = useState(initialCategories); const [filters, setFilters] = useState(emptyFilters); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<Expense | null | "new">(null); const [detail, setDetail] = useState<ExpenseDetail | null>(null); const [voiding, setVoiding] = useState<Expense | null>(null); const [managingCategories, setManagingCategories] = useState(false); const sequence = useRef(0); const monthRef = useRef(initialMonth); const filtersRef = useRef(emptyFilters); const pageRef = useRef(initialData.page);
  const queryFor = (value: Filters, page: number, selectedMonth: string): ExpenseListQuery => ({ ...(value.dateFrom || value.dateTo ? { dateFrom: value.dateFrom || `${selectedMonth}-01`, dateTo: value.dateTo || getMonthBounds(selectedMonth).to } : { month: selectedMonth }), categoryId: value.categoryId || undefined, type: value.type as ExpenseCategoryType || undefined, paymentMethodId: value.paymentMethodId || undefined, status: value.status as "active" | "voided" || undefined, text: value.text || undefined, page, pageSize: 10 });
  const load = async ({ selectedMonth = monthRef.current, selectedFilters = filtersRef.current, page = pageRef.current }: { selectedMonth?: string; selectedFilters?: Filters; page?: number } = {}) => { const current = ++sequence.current; setLoading(true); setError(null); try { const [next, nextSummary] = await Promise.all([client.list(queryFor(selectedFilters, page, selectedMonth)), client.summary(selectedMonth)]); if (current !== sequence.current) return; pageRef.current = next.page; setResult(next); setSummary(nextSummary); } catch (caught) { if (current === sequence.current) setError(caught instanceof Error ? caught.message : "No se pudieron cargar los gastos."); } finally { if (current === sequence.current) setLoading(false); } };
  const changeFilter = (key: keyof Filters, value: string) => { const next = { ...filtersRef.current, [key]: value }; filtersRef.current = next; pageRef.current = 1; setFilters(next); void load({ selectedFilters: next, page: 1 }); };
  const changeMonth = (value: string) => { const bounds = getMonthBounds(value); const next = { ...filtersRef.current, dateFrom: filtersRef.current.dateFrom ? bounds.from : "", dateTo: filtersRef.current.dateTo ? bounds.to : "" }; monthRef.current = value; filtersRef.current = next; pageRef.current = 1; setMonth(value); setFilters(next); void load({ selectedMonth: value, selectedFilters: next, page: 1 }); };
  const refresh = () => load();
  const openDetail = async (expense: Expense) => { setError(null); try { setDetail(await client.get(expense.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo abrir el detalle."); } };
  const manageCategories = () => { setEditing(null); setManagingCategories(true); };
  const hasActiveCategories = categories.some((item) => item.isActive);
  // Redirect the existing create trigger before an unusable editor can render.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (editing === "new" && !hasActiveCategories) { manageCategories(); toast.info("Creá o reactivá una categoría antes de registrar un gasto."); } }, [editing, hasActiveCategories]);
  const metricCards = [{ label: "Ingresos brutos", value: summary.grossIncome }, { label: "Comisiones", value: summary.commission }, { label: "Neto barbería", value: summary.barbershopNet }, { label: "Gastos", value: summary.expenses }, { label: "Resultado operativo", value: summary.operatingResult }];
  const bounds = getMonthBounds(month); const control = "h-10 rounded-xl border border-input bg-white px-3 text-sm";
  return <div className="space-y-6"><section aria-label="Resumen mensual"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium">Resumen del mes completo</p><p className="text-xs text-muted-foreground">No cambia con los filtros del listado.</p></div><label className="space-y-1"><span className="sr-only">Mes contable</span><Input aria-label="Mes contable" type="month" value={month} max={today.slice(0, 7)} onChange={(e) => changeMonth(e.target.value)} /></label></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metricCards.map((item, index) => <Card key={item.label} className={index === 4 ? "bg-[#20231f] text-white" : "bg-white"}><CardContent className="p-4"><p className={`text-xs ${index === 4 ? "text-white/60" : "text-muted-foreground"}`}>{item.label}</p><p className="mt-2 text-xl font-semibold">{money.format(item.value)}</p></CardContent></Card>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-3">{(["fixed", "variable", "supplies"] as const).map((type) => <div key={type} className="rounded-2xl border border-primary/10 bg-primary/[0.04] px-4 py-3"><p className="text-xs text-muted-foreground">{typeLabels[type]}</p><p className="font-semibold">{money.format(summary[`${type}Total`])}</p></div>)}</div></section>
  <section className="rounded-[1.6rem] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><h2 className="font-semibold">Movimientos</h2><p className="text-sm text-muted-foreground">{result.total} registros · filtrado: {money.format(result.metrics.total)}</p></div><div className="flex max-w-full flex-wrap gap-2"><Button variant="outline" onClick={() => setManagingCategories(true)}><Settings2 /> Categorías</Button><Button onClick={() => setEditing("new")}><Plus /> Nuevo gasto</Button></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Input aria-label="Buscar gastos" placeholder="Buscar concepto o notas" value={filters.text} onChange={(e) => changeFilter("text", e.target.value)} /><select aria-label="Filtrar por categoría" className={control} value={filters.categoryId} onChange={(e) => changeFilter("categoryId", e.target.value)}><option value="">Todas las categorías</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filtrar por tipo" className={control} value={filters.type} onChange={(e) => changeFilter("type", e.target.value)}><option value="">Todos los tipos</option>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar por estado" className={control} value={filters.status} onChange={(e) => changeFilter("status", e.target.value)}><option value="">Todos los estados</option><option value="active">Activos</option><option value="voided">Anulados</option></select><Input aria-label="Fecha desde" type="date" min={bounds.from} max={bounds.to} value={filters.dateFrom} onChange={(e) => changeFilter("dateFrom", e.target.value)} /><Input aria-label="Fecha hasta" type="date" min={bounds.from} max={bounds.to} value={filters.dateTo} onChange={(e) => changeFilter("dateTo", e.target.value)} /><select aria-label="Filtrar por medio de pago" className={control} value={filters.paymentMethodId} onChange={(e) => changeFilter("paymentMethodId", e.target.value)}><option value="">Todos los medios</option>{paymentMethods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button variant="outline" onClick={() => { filtersRef.current = emptyFilters; pageRef.current = 1; setFilters(emptyFilters); void load({ selectedFilters: emptyFilters, page: 1 }); }}>Limpiar filtros</Button></div><div className="mt-4 flex items-start gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><WalletCards className="mt-0.5 size-4 shrink-0" /><p>El medio de pago es un dato administrativo. Registrar gastos no descuenta efectivo ni altera Caja en esta versión.</p></div></section>
  {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
  <section aria-busy={loading} aria-label="Listado de gastos" className={loading ? "opacity-60" : ""}>{result.items.length ? <><div className="hidden overflow-x-auto rounded-2xl bg-white shadow-sm xl:block"><table className="w-full min-w-[52rem] text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="p-4">Fecha</th><th>Concepto</th><th>Categoría / tipo</th><th>Medio</th><th>Estado</th><th className="text-right">Importe</th><th className="p-4 text-right">Detalle</th></tr></thead><tbody>{result.items.map((item) => <tr key={item.id} className="border-t hover:bg-muted/30"><td className="p-4">{item.accountingDate}</td><td><p className="break-words font-medium">{item.concept}</p><p className="text-xs text-muted-foreground">Act. {new Date(item.updatedAt).toLocaleDateString("es-AR")}</p></td><td>{item.categoryName}<p className="text-xs text-muted-foreground">{typeLabels[item.categoryType]}</p></td><td>{item.paymentMethodName ?? "—"}</td><td><Badge variant={item.status === "active" ? "secondary" : "destructive"}>{item.status === "active" ? "Activo" : "Anulado"}</Badge></td><td className="text-right font-semibold">{money.format(item.amount)}</td><td className="p-4 text-right"><Button size="sm" variant="ghost" aria-label={`Ver detalle de ${item.concept}`} onClick={() => void openDetail(item)}>Ver</Button></td></tr>)}</tbody></table></div><div className="grid gap-3 xl:hidden">{result.items.map((item) => <button type="button" key={item.id} onClick={() => void openDetail(item)} className="rounded-2xl bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-semibold">{item.concept}</p><p className="break-words text-xs text-muted-foreground">{item.accountingDate} · {item.categoryName}</p></div><p className="shrink-0 font-semibold">{money.format(item.amount)}</p></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span className="break-words">{item.paymentMethodName ?? "Sin medio informado"}</span><span>{item.status === "active" ? "Activo" : "Anulado"}</span></div></button>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><Button variant="outline" disabled={loading || result.page <= 1} onClick={() => void load({ page: result.page - 1 })}>Anterior</Button><span className="text-sm text-muted-foreground">Página {result.page} de {Math.max(result.totalPages, 1)}</span><Button variant="outline" disabled={loading || result.page >= result.totalPages} onClick={() => void load({ page: result.page + 1 })}>Siguiente</Button></div></> : <div className="flex min-h-56 flex-col items-center justify-center rounded-[1.6rem] bg-white text-center"><ReceiptText className="size-6 text-primary" /><h3 className="mt-3 font-semibold">No hay gastos para mostrar</h3><p className="text-sm text-muted-foreground">Cambiá los filtros o registrá el primer movimiento.</p></div>}</section>
  {editing === "new" && hasActiveCategories && <ExpenseEditorDialog mode="create" categories={categories} paymentMethods={paymentMethods} today={today} onClose={() => setEditing(null)} onManageCategories={manageCategories} onSave={async (input) => { await client.create(input); setEditing(null); setDetail(null); await refresh(); toast.success("Gasto registrado."); }} />}
  {editing && editing !== "new" && <ExpenseEditorDialog mode="edit" expense={editing} categories={categories} paymentMethods={paymentMethods} today={today} onClose={() => setEditing(null)} onManageCategories={manageCategories} onSave={async (input) => { await client.update(editing.id, input); setEditing(null); setDetail(null); await refresh(); toast.success("Gasto actualizado."); }} />}
  {detail && <ExpenseDetailSheet detail={detail} onClose={() => setDetail(null)} onEdit={() => { setEditing(detail.expense); setDetail(null); }} onVoid={() => { setVoiding(detail.expense); setDetail(null); }} />}
  {voiding && <ExpenseVoidDialog concept={voiding.concept} onClose={() => setVoiding(null)} onConfirm={async (reason) => { await client.void(voiding.id, { reason, expectedUpdatedAt: voiding.updatedAt }); setVoiding(null); await refresh(); toast.success("Gasto anulado."); }} />}
  {managingCategories && <ExpenseCategoriesDialog categories={categories} onChange={setCategories} onClose={() => setManagingCategories(false)} client={categoryClient} />}
  </div>;
};
