import type { Metadata } from "next";
import { ExpensesWorkspace } from "@/components/expenses/expenses-workspace";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { requireManagerPage } from "@/lib/auth/authorization";
import { getBuenosAiresMonth, getBuenosAiresToday } from "@/lib/expenses/date";
import { getExpenseMonthSummary, listExpenseCategories, listExpenses } from "@/lib/expenses/service";
import { paymentMethodRepository } from "@/lib/payment-methods/repository";
export const metadata: Metadata = { title: "Gastos", description: "Administrá gastos y resultado operativo de Bastardos Barbería." };
export default async function ExpensesPage() { const { user } = await requireManagerPage(); const month = getBuenosAiresMonth(); const [data, summary, categories, paymentMethods] = await Promise.all([listExpenses(user, { month, page: 1, pageSize: 10 }), getExpenseMonthSummary(user, month), listExpenseCategories(user), paymentMethodRepository.list(true)]); return <><header className="sticky top-0 z-20 border-b border-black/5 bg-[#f1f0ed]/90 backdrop-blur-xl xl:rounded-t-[2rem]"><div className="mx-auto flex h-16 w-full max-w-[1600px] items-center gap-3 px-5 md:px-7 xl:px-8"><SidebarTrigger className="-ml-1" /><div><p className="text-xs text-muted-foreground">Estructura operativa</p><h1 className="font-semibold">Gastos</h1></div></div></header><main className="mx-auto w-full max-w-[1600px] flex-1 px-5 py-5 pb-10 md:px-7 xl:px-8 xl:py-7"><div className="mb-6 max-w-3xl"><p className="text-xs font-semibold tracking-[0.2em] text-primary uppercase">Resultado del negocio</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em] sm:text-3xl">Entendé qué cuesta operar cada mes</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Registrá egresos, separá costos y comparalos con el neto real de la barbería.</p></div><ExpensesWorkspace initialData={data} initialSummary={summary} initialCategories={categories} paymentMethods={paymentMethods} initialMonth={month} today={getBuenosAiresToday()} /></main></>; }
