export type PaymentMethod = "cash" | "transfer";
export type UserRole = "owner" | "admin" | "employee";
export type Employee = { id: string; firstName: string; lastName: string };
export type Customer = Employee & { phone?: string };
export type Service = { id: string; name: string; price: number };
export type Product = { id: string; name: string; price: number; stock: number };
export type CurrentUser = Employee & { role: UserRole };
export type IncomeFormEmployee = CurrentUser & { isActive: boolean; serviceCommissionRate: number; productCommissionRate: number };
export type IncomeFormData = { currentUser: CurrentUser; customers: Customer[]; services: Service[]; products: Product[]; employees?: IncomeFormEmployee[] };
export type IncomeProductInput = { productId: string; quantity: number; grantFullCommission: boolean };
export type IncomePayment = { method: PaymentMethod; amount: number };
export type CreateIncomeInput = {
  requestId: string;
  employeeId: string;
  customerId: string | null;
  serviceId: string | null;
  products: IncomeProductInput[];
  payments: IncomePayment[];
  grantFullServiceCommission: boolean;
};
export type IncomeStatus = "active" | "voided";
export type IncomeKind = "service" | "products" | "combined";
export type IncomeListService = Service & { commission: import("@/types/income-commissions").IncomeItemCommissionSnapshot };
export type IncomeListProduct = { id: string; name: string; unitPrice: number; quantity: number; commission: import("@/types/income-commissions").IncomeItemCommissionSnapshot };
export type IncomeListItem = {
  id: string; createdAt: string; businessDate: string; employee: Employee; customer: Employee | null;
  service: IncomeListService | null; products: IncomeListProduct[]; paymentMethod: PaymentMethod; payments?: IncomePayment[]; registeredBy?: Employee; commission?: import("@/types/income-commissions").IncomeCommissionSnapshot; total: number; status: IncomeStatus;
};
export type Income = IncomeListItem;
export type IncomeService = { create(input: CreateIncomeInput): Promise<Income> };
export type IncomeListFilters = { query: string; dateFrom: string; dateTo: string; employeeId: string; paymentMethod: PaymentMethod | "all"; kind: IncomeKind | "all"; status?: IncomeStatus | "all" };
export type IncomeListQuery = { query?: string; dateFrom?: string; dateTo?: string; userId?: string; paymentMethod?: PaymentMethod; kind?: IncomeKind; status?: IncomeStatus; page: number; pageSize: number };
export type IncomeListMetrics = { grossTotal?: number; total?: number; commissionTotal?: number; barbershopNet?: number; count: number; average: number; cashTotal: number; transferTotal: number };
export type IncomePagination = { page: number; pageSize: number; total: number; totalPages: number };
export type PaginatedIncomes = { items: IncomeListItem[]; metrics: IncomeListMetrics; pagination: IncomePagination };
export type IncomeListData = { currentUser: CurrentUser; employees: Employee[]; incomes: IncomeListItem[] };
