import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const sql = readFileSync("supabase/queries/026_operating_expenses.sql", "utf8");
const readme = readFileSync("supabase/queries/README.md", "utf8");
describe("migration 026", () => {
  it("secures all tables and exposes the complete RPC contract", () => { for (const table of ["expense_categories", "expenses", "expense_revisions"]) expect(sql).toContain(`alter table public.${table} enable row level security`); for (const rpc of ["create_expense","update_expense","void_expense","get_expense","list_expenses","get_expense_month_summary","list_expense_categories","create_expense_category","update_expense_category","delete_expense_category"]) expect(sql).toContain(`function public.${rpc}`); expect(sql).toContain("to service_role"); });
  it("keeps Caja isolated and payment snapshots safe", () => { expect(sql).not.toMatch(/insert into public\.daily_cash|update public\.daily_cash|delete from public\.daily_cash/); expect(sql).toContain("payment_method_id uuid references public.payment_methods(id) on delete restrict"); expect(sql).toContain("exists(select 1 from public.expenses where payment_method_id=target_payment_method_id)"); expect(sql).toContain("CASH_PAYMENT_METHOD_PROTECTED"); });
  it("uses the canonical concept, notes and voided contract", () => { expect(sql).toContain("concept text not null"); expect(sql).toContain("notes text"); expect(sql).toContain("status in ('active','voided')"); expect(sql).not.toContain("description text"); expect(sql).not.toContain("status='void'"); });
  it("summarizes all active income source types without narrowing source_type", () => { const summary = sql.slice(sql.indexOf("create function public.get_expense_month_summary")); expect(summary).toContain("from public.incomes where status='active'"); expect(summary).not.toContain("source_type="); });
  it("serializes idempotency before catalog validation with the canonical conflict", () => { const create = sql.slice(sql.indexOf("create function public.create_expense(actor_user_id"), sql.indexOf("create function public.update_expense(actor_user_id")); expect(create).toContain("expense-request:"); expect(create.indexOf("pg_advisory_xact_lock")).toBeLessThan(create.indexOf("from public.expense_categories")); expect(create.indexOf("where actor_id=actor_user_id")).toBeLessThan(create.indexOf("from public.expense_categories")); expect(create).toContain("EXPENSE_REQUEST_CONFLICT"); });
  it("preserves lifecycle locks, duplicate mapping and optimistic voids", () => { expect(sql).toContain("bastardos_payment_method_lifecycle"); expect(sql.match(/exception when unique_violation/g)).toHaveLength(2); const voidRpc = sql.slice(sql.indexOf("create function public.void_expense"), sql.indexOf("create function public.get_expense")); expect(voidRpc).toContain("expected_updated_at timestamptz"); expect(voidRpc.indexOf("EXPENSE_CONFLICT")).toBeLessThan(voidRpc.indexOf("EXPENSE_NOT_ACTIVE")); });
  it("documents rollback-only executable acceptance for every critical boundary", () => { const acceptance = readme.slice(readme.indexOf("Validate migration `026`"), readme.indexOf("Verify the automatic cash objects")); expect(acceptance).toContain("begin;"); expect(acceptance).toContain("rollback;"); for (const contract of ["MANAGER_REQUIRED", "EXPENSE_CATEGORY_DUPLICATE", "EXPENSE_REQUEST_CONFLICT", "EXPENSE_CONFLICT", "EXPENSE_NOT_ACTIVE", "expense_revisions", "list_expenses", "get_expense_month_summary", "PAYMENT_METHOD_IN_USE", "daily_cash_registers", "daily_cash_sales", "daily_cash_payment_totals", "daily_cash_adjustments", "daily_cash_adjustment_payments"]) expect(acceptance).toContain(contract); });
});
